# Generated by Django 4.0.4 on 2022-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0004_remove_instrumentmodel_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Գործընկերներ', 'verbose_name_plural': 'Գործընկերներ'},
        ),
    ]
