# Generated by Django 4.0.4 on 2022-05-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0005_alter_partner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Գործընկեր', 'verbose_name_plural': 'Գործընկերներ'},
        ),
    ]
