# Generated by Django 4.0.4 on 2022-05-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0007_alter_banneritems_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcontent',
            options={'verbose_name': 'Սարքավորուման կոնտենտ', 'verbose_name_plural': 'Սարքավորումների կոնտենտներ'},
        ),
    ]
