# Generated by Django 4.0.4 on 2022-05-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Կապ ադմինիստրատորի հետ', 'verbose_name_plural': 'Կապ ադմինիստրատորի հետ'},
        ),
    ]
